{
  "message" : "[0/1] Planning build\nBuilding for debugging...\n[0/2] Write swift-version-24593BA9C3E375BF.txt\nBuild complete! (0.11s)\nTest Suite 'All tests' started at 2025-01-08 18:59:32.714\nTest Suite 'debug.xctest' started at 2025-01-08 18:59:32.715\nTest Suite 'debug.xctest' passed at 2025-01-08 18:59:32.715\n\t Executed 0 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds\nTest Suite 'All tests' passed at 2025-01-08 18:59:32.715\n\t Executed 0 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds\nâ—‡ Test run started.\nâ†³ Testing Library Version: 6.0.2 (cd448bbe5cc989d)\nâ—‡ Suite MultipleWithExceptionTests started.\nâ—‡ Test \"test Sub\" started.\nâ—‡ Test \"test Mul\" started.\nâ—‡ Test \"test Throw\" started.\nâ—‡ Test \"test Add\" started.\nMultipleWithException/MultipleWithException.swift:16: Fatal error: Oh noes!\nâœ” Test \"test Sub\" passed after 0.001 seconds.\nâœ˜ Test \"test Throw\" recorded an issue at MultipleWithExceptionTests.swift:23:5: Expectation failed: try! throwErr(2, 3) == 5\nâœ” Test \"test Add\" passed after 0.001 seconds.\nâœ˜ Test \"test Throw\" failed after 0.001 seconds with 1 issue.\n\n*** Signal 4: Backtracing from 0x7fe77c2038d0... done ***\n\n*** Program crashed: Illegal instruction at 0x00007fe77c2038d0 ***\n\nThread 0 \"MultipleWithExc\":\n\n0      0x00007fe77b2a45db <unknown> in libc.so.6\n1 [ra] 0x00007fe77bc570d8 _dispatch_sigsuspend + 23 in libdispatch.so\n2 [ra] 0x00007fe77b2891d6 <unknown> in libc.so.6\n3 [ra] 0x00007fe77b28928b <unknown> in libc.so.6\n\nThread 1:\n\n0      0x00007fe77b2f7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fe77b303d83 <unknown> in libc.so.6\n\nThread 2:\n\n0      0x00007fe77b389042 <unknown> in libc.so.6\n1 [ra] 0x00007fe77bc5e405 _dispatch_event_loop_drain + 52 in libdispatch.so\n\nThread 3 crashed:\n\n 0                  0x00007fe77c2038d0 _assertionFailure(_:_:file:line:flags:) + 496 in libswiftCore.so\n 1 [ra]             0x000055664691d521 mul(_:_:) + 192 in MultipleWithExceptionPackageTests.xctest at /solution/Sources/MultipleWithException/MultipleWithException.swift:16:5\n 2 [ra] [inlined]   0x000055664694d8d6 freestanding macro expansion #1 of expect in module MultipleWithExceptionTests file MultipleWithExceptionTests.swift line 18 column 5 in MultipleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_26MultipleWithExceptionTests0037MultipleWithExceptionTestsswift_emGFlfMX17_4_6expectfMf_.swift:1:32\n 3 [ra]             0x000055664694d8d6 MultipleWithExceptionTests.testMul() + 165 in MultipleWithExceptionPackageTests.xctest at /solution/Tests/MultipleWithExceptionTests/MultipleWithExceptionTests.swift:18:5\n 4 [ra]             0x000055664694b6ee closure #2 in static MultipleWithExceptionTests.$s26MultipleWithExceptionTestsAAV7testMul4TestfMp_13functestMul__fMu0_@Sendable () + 45 in MultipleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_26MultipleWithExceptionTestsAAV7testMul4TestfMp_.swift:14:90\n 5 [async]          0x00007fe77c72d270 __ifMainActorIsolationEnforced<A>(_:else:) in libTesting.so\n 6 [async]          0x000055664694ac10 static MultipleWithExceptionTests.$s26MultipleWithExceptionTestsAAV7testMul4TestfMp_13functestMul__fMu0_@Sendable () in MultipleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_26MultipleWithExceptionTestsAAV7testMul4TestfMp_.swift:3\n 7 [async]          0x000055664694bb00 implicit closure #1 in static MultipleWithExceptionTests.$s26MultipleWithExceptionTestsAAV7testMul4TestfMp_43__ðŸŸ $test_container__function__functestMul__fMu_.__tests.getter in MultipleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_26MultipleWithExceptionTestsAAV7testMul4TestfMp_.swift:29\n 8 [async]          0x00007fe77c6f50e0 closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n 9 [async] [thunk]  0x00007fe77c6feb80 partial apply for closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n10 [async]          0x00007fe77c6b97e0 specialized static Issue.withErrorRecording(at:configuration:isolation:_:) in libTesting.so\n11 [async]          0x00007fe77c6f4960 closure #1 in Runner._runTeserror: Exited with unexpected signal code 4\ntCase(_:within:) in libTesting.so\n12 [async] [thunk]  0x00007fe77c6febc0 partial apply for closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n13 [async]          0x00007fe77c6ed7a0 specialized static Test.Case.withCurrent<A>(_:perform:) in libTesting.so\n14 [async]          0x00007fe77c6f4490 Runner._runTestCase(_:within:) in libTesting.so\n15 [async]          0x00007fe77c6f4000 closure #2 in Runner._runTestCases<A>(_:within:) in libTesting.so\n16 [async] [thunk]  0x00007fe77c6feb70 partial apply for closure #2 in Runner._runTestCases<A>(_:within:) in libTesting.so\n17 [async]          0x00007fe77c6fa300 specialized closure #1 in closure #1 in Runner._forEach<A, B>(in:for:_:) in libTesting.so\n18 [async] [thunk]  0x00007fe77c6feb60 partial apply for specialized closure #1 in closure #1 in Runner._forEach<A, B>(in:for:_:) in libTesting.so\n19 [async] [system] 0x00007fe77bef4190 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) in libswift_Concurrency.so\n\nThread 4:\n\n0      0x00007fe77b2f7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fe77b303d83 <unknown> in libc.so.6\n\nThread 5:\n\n0      0x00007fe77b2f7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fe77b303d83 <unknown> in libc.so.6\n\nThread 6:\n\n0      0x00007fe77b2f7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fe77b303d83 <unknown> in libc.so.6\n\nThread 7:\n\n0      0x00007fe77b2f7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fe77b303d83 <unknown> in libc.so.6\n\nThread 8:\n\n0      0x00007fe77b2f7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fe77b303d83 <unknown> in libc.so.6\n\n\nRegisters:\n\nrax 0x0000000000000000  0\nrdx 0x0000556646998823  46 61 74 61 6c 20 65 72 72 6f 72 00 4f 68 20 6e  Fatal errorÂ·Oh n\nrcx 0x0000000000000002  2\nrbx 0x00007fe09a766ed2  140602640854738\nrsi 0x8000000000000000  9223372036854775808\nrdi 0x00007fe764002390  20 a0 5d 7c e7 7f 00 00 25 00 00 00 00 00 00 00   Â ]|Ã§Â·Â·Â·%Â·Â·Â·Â·Â·Â·Â·\nrbp 0x00007fe7737fd890  f0 d8 7f 73 e7 7f 00 00 21 d5 91 46 66 55 00 00  Ã°Ã˜Â·sÃ§Â·Â·Â·!Ã•Â·FfUÂ·Â·\nrsp 0x00007fe7737fd7f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·\n r8 0x00007fe7640008e0  02 00 00 00 07 00 01 00 05 00 06 00 01 00 07 00  Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·\n r9 0x0000000000000007  7\nr10 0x00007fe7640023a0  d2 6e 76 9a e0 7f 00 00 f0 f8 75 d1 49 84 42 e5  Ã’nvÂ·Ã Â·Â·Â·Ã°Ã¸uÃ‘IÂ·BÃ¥\nr11 0xe5428449d175f8f0  16519911835730049264\nr12 0x00005566469983d0  4d 75 6c 74 69 70 6c 65 57 69 74 68 45 78 63 65  MultipleWithExce\nr13 0x2173656f6e20684f  2410381754836740175\nr14 0xe800000000000000  16717361816799281152\nr15 0x000000000000000b  11\nrip 0x00007fe77c2038d0  0f 0b 48 83 ec 08 48 8d 05 23 9e 2e 00 48 8d 3d  Â·Â·HÂ·Ã¬Â·HÂ·Â·#Â·.Â·HÂ·=\n\nrflags 0x0000000000010286  SF PF\n\ncs 0x0033  fs 0x0000  gs 0x0000\n\n\nImages (16 omitted):\n\n0x0000556646914000â€“0x0000556646994cb0 <no build ID>                            MultipleWithExceptionPackageTests.xctest /solution/.build/x86_64-unknown-linux-gnu/debug/MultipleWithExceptionPackageTests.xctest\n0x00007fe77b25f000â€“0x00007fe77b40ec8d 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6 libc.so.6                                /usr/lib/x86_64-linux-gnu/libc.so.6\n0x00007fe77bc21000â€“0x00007fe77bc5f9c1 <no build ID>                            libdispatch.so                           /usr/lib/swift/linux/libdispatch.so\n0x00007fe77be88000â€“0x00007fe77bf0dfc0 2abcae414e1196cafa29e10b5161ebbb05add43b libswift_Concurrency.so                  /usr/lib/swift/linux/libswift_Concurrency.so\n0x00007fe77bf21000â€“0x00007fe77c4b5ed0 2c7478c6e1a4d502046f5650534759839f0eb256 libswiftCore.so                          /usr/lib/swift/linux/libswiftCore.so\n0x00007fe77c62c000â€“0x00007fe77c7660d8 <no build ID>                            libTesting.so                            /usr/lib/swift/linux/libTesting.so\n\nBacktrace took 0.02s\n\n",
  "status" : "error",
  "tests" : [

  ],
  "version" : 3
}